project:
  type: website
  output-dir: docs

website:
  title: "R for Graph and Table"
  search: true
  back-to-top-navigation: true
  reader-mode: true
  
  navbar:
    background: info
    left:
      - text: "主页"
        href: index.qmd
      - text: "图"
        href: Graph.qmd
      - text: "表"
        href: Table.qmd
      - text: "参考文献"
        href: references.qmd
    
        
  sidebar:
    - title: "Graph"
      style: "docked"
      background: "#ffd9e6"
      foreground: "#87cefa"
      border: true
      alignment: left
      collapse-level: 4
      contents: 
        - Graph.qmd

        - section: "条图"
          contents: 
            - 条图.qmd
        - section: "点图"
          contents: 
            - dotplot.qmd
            # - 曼哈顿图.qmd
            # - 克利夫兰点图.qmd
        - section: "线图"
          contents: 
            - 生存曲线.qmd
            - 折线图.qmd
            - 回归曲线.qmd
       
        - section: "块图"
          contents: 
            - 相关图.qmd
            - 热图.qmd
            
    - title: "Table"
      contents: 
        - Table.qmd
       
       
knitr: 
  opts_chunk: 
    comment: "#>"
    collapse: TRUE

execute:
  cache: true
  message: false
  warning: true

toc-depth: 4
number-sections: true
number-depth: 4
code-fold: show
code-link: true
code-tools: true

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    fig-format: svg

editor: visual

