project:
  type: website
  output-dir: docs

website:
  title: "R for Graph and Table"
  search: true
  back-to-top-navigation: true
  reader-mode: true
  
  navbar:
    background: info
    left:
      - text: "主页"
        href: index.qmd
      - text: "图"
        href: Graph.qmd
      - text: "表"
        href: Table.qmd
      - text: "引用"
        href: about.qmd
    
        
  sidebar:
    - title: "Graph"
      style: "docked"
      background: "#ffd9e6"
      foreground: "#87cefa"
      border: true
      alignment: left
      collapse-level: 4
      contents: 
        - Graph.qmd
        - 01.qmd
        - 02.qmd
        - section: "条图"
       
    - title: "Table"
      contents: 
        - Table.qmd
       
       
knitr: 
  opts_chunk: 
    comment: "#>"
    collapse: TRUE

execute:
  cache: true
  message: false
  warning: true

toc-depth: 4
number-sections: true
number-depth: 4
code-fold: show
code-link: true
code-tools: true

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    fig-format: svg

editor: visual

